# Generated by Django 5.1.5 on 2025-01-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='app',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
                ('idade', models.FloatField(verbose_name='idade')),
                ('Date_nascimento', models.DateField(verbose_name='Date De nascimento')),
                ('criado_em', models.DateField(auto_now_add=True, verbose_name='data de criaçao')),
                ('atualizado', models.DateTimeField(auto_now=True, verbose_name='data de edicao')),
            ],
        ),
    ]
